export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS';
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS';

export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS';
export const LOAD_TRIP_SUCCESS = 'LOAD_TRIP_SUCCESS';
