export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_DELETE_SUCCESS = 'TOKEN_DELETE_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const RESET_USER = 'RESET_USER';
export const LOAD_USER_FAILED = 'LOAD_USER_FAILED';

export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS';
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS';

export const LOAD_TRIPS_SUCCESS = 'LOAD_TRIPS_SUCCESS';
export const LOAD_TRIP_SUCCESS = 'LOAD_TRIP_SUCCESS';
